### ISSUE TITLE
Error: Wrong index

### ISSUE THREAD

**Issue by ArthurYidi** [JXA-Cookbook/JXA-Cookbook#36]
In the cookbook examples using `app.windows.push(app.Window())` leads to `Error: Wrong index`

I recommend changing the examples to use`app.Window().make();`

**Comment by BrokenFreelancer** [comment]
@ArthurYidi  @Tatsh  There are many issues with the way `Document()`, `Window()`, `documents`, `windows` interact with the `.push()` and `.make()` methods .

Since this issue was never closed, maybe it could be renamed to address the larger topic?
What page of the wiki is this discussed on? I can't find it.

As far as I have been able to determine, the issue doesn't have much to do with differences between 10.10 and 10.11, but rather with the absence of DOM in JXA.

What I mean is: I think `Window` and `Document` + the corresponding arrays (`windows`, `documents`) look familiar in JXA because of the resemblance to their DOM counterparts, but actually, they are newly constructed prototypes defined by Apple. 
Now, the DOM has been around for 19 years and the DOM versions of `Window` and `Document`can now be expected to behave homogeneously across browsers.

In JXA, as far as I could tell, there is no such homogeneity across apps as of now.
In my experience, depending on the application you're targeting, in some cases neither `app.windows.push(app.Window()) ;` nor  `app.Window().make();`  will work because a certain app might require instead `app.documents.push(app.Window()) ;` and/or `app.Document().make();`.
In certain apsp `app.windows.push(app.Window()) ;` might genuinely be a `wrong index` because `windows` is an array and you have to determine how the array `windows` for that specific app is constructed in order to know if you can push on to it a new `Window` object.

This topic is not really covered in the documentation, so my deductions are based totally on trial and error, I might have missed something somewhere that proves me wrong, but in case I'd appreciate some feedback or at least to be pointed to the page on the wiki that was addressing this.

**Comment by Tatsh** [comment]
Closing due to age.
