### ISSUE TITLE
How Do I Get Outlook 2011 Msg by ID using JXA?

### ISSUE THREAD

**Issue by JMichaelTX** [JXA-Cookbook/JXA-Cookbook#38]
Any ideas on what the JXA equivalent of this AppleScript is?

```applescript
tell application "Microsoft Outlook"
  open message id 123
  activate
end tell
```

I've tried just about everything, but nothing works, including these:

```javascript
var olApp = Application("Microsoft Outlook");
olApp.includeStandardAdditions = true;

//--- NONE of These Work ---

var oMsg = olApp.Message({id: 123});
var oMsg = olApp.message({id: 123});
var oMsg  = olApp.messages({id: 123});
var oMsg  = olApp.messages()({id: 123});

//--- This Works, but is VERY SLOW ---
var oMsg  = olApp.messages.whose({id: 123});

//-- Once I Have an Object Ref to the Msg, this should work ---
olApp.open(oMsg);
```

**Comment by Tatsh** [comment]
I've looked at this with Outlook 2016 and no luck plus I'm getting crashes on calling methods like `defaultAccount()` from the `Application` instance:

```
2017-10-20 13:47:02.183 osascript[43416:5941867] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString appendString:]: nil argument'
```

Even running `console.log(app)` crashes for me with this.

I'm guessing if this happens it means the argument expects a string but this is really hard to figure out because the documentation is very unclear.

Open the library in Script Editor and add Outlook to it.

![screen shot 2017-10-20 at 13 50 08](https://user-images.githubusercontent.com/724848/31834906-9d7f6582-b59d-11e7-9cbc-46ff8612f3e5.png)

**Comment by johnelm** [comment]
@JMichaelTX  @Tatsh I think this might be what you were looking for:

```
const outlookApp = Application( "Microsoft Outlook" );

let message = outlookApp.messages.byId( 123 );
console.log( message.subject() );
```

**Comment by JMichaelTX** [comment]
@johnelm , thank you so much!  That is so simple, yet completely undiscoverable by me.
I suspect that is a pattern that will apply to other apps as well.  We probably need to add this to the Wiki somewhere.

I just verified this, so I'm closing this issue.

**Comment by johnelm** [comment]
hey @JMichaelTX ..  cool, I'm glad you got it sorted.

Yep I think it is a pattern, in all apps it seems..  [Both id ( `byId( id )` ) and even name ( `byName( name )` )](https://developer.apple.com/library/content/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/Articles/OSX10-10.html#//apple_ref/doc/uid/TP40014508-CH109-SW9) can be used to obtain a specific element from an 'element array'.  `byName` puzzles me though - I don't think name would necessarily be unique, nor would it be present (or relevant) in all cases. :)
