### ISSUE TITLE
Menu Items scripting

### ISSUE THREAD

**Issue by petolino** [JXA-Cookbook/JXA-Cookbook#39]
The wiki on System Events says that menu items can't be scripted unless osascript is given Accessibility access, and recommends using tccutil.py to do this.  However, as of MacOS Sierra,
tccutil.py can no longer be used to grant access without disabling SIP:

    https://github.com/jacobsalmela/tccutil/issues/18

Please mention this in the wiki.

**Comment by sancarn** [comment]
You can change this on the wiki yourself, FYI. The wiki is open to editing for everyone.

**Comment by Tatsh** [comment]
This is no longer an issue on Mojave. macOS 10.14 will have a section named *Automation* under *Security & Privacy* / *Privacy*.

**Comment by BrokenFreelancer** [comment]
That whole section seems quite misleading even before Mojave?
Has adding `osascript` to the accessibility panel ever really been necessary?

The sections states `osascript` can't be added to the _Security&Privacy / Accessibility_ panel without that python script.  That's misleading, it can be done, it maybe takes a little longer and involves using sqlite3 which is pretty advanced, but is giving a python script you haven't written the ability to change the security settings of your laptop really the first advisable course of action? (which now even requires bypassing SIP???)

Anyway, as I was saying, I don't think adding `osascript` to the accessibility panel was ever needed.
I am 99.99% sure that adding Terminal to the same panel has always granted accessibility permission to all command lines, including `osascript` and, since Terminal is an app, this has always been possible in the GUI.

So, could I edit that section and completely do away with the python script or just mention it in an end note?

@Tatsh Maybe I could redo the _Until macOS 10.13 High Sierra_ and you could add _10.14 Mojave_ ?

**Comment by BrokenFreelancer** [comment]
`tccutil` and `tccutil.py`are two different things. `tccutil` is a command included in macOS by Apple that resets the privacy database.

`tccutil.py` is a third party command that runs `squlite3` and can edit `tcc.db` through a python script.  It can apply quite a few different changes depending on the arguments you add to it.
It's a smart script, but giving people a tool to automate `sqlite3` without knowing exactly what's going on... not the best security practice IMO, probably why SIP now tries to stop it.

Anyway, it's not actually made specifically for `osascript`.

I think the idea one needs to add `osascript` to the _Security&Privacy / Accessibility_ comes from [this blog post](https://jacobsalmela.com/2014/07/26/os-x-yosemite-osascript-enabling-access-assistive-devices/) because they always pop up together, but I am pretty sure the guy just overlooked he could simply add Terminal to the panel.
