### ISSUE TITLE
Can't import a custom framework

### ISSUE THREAD

**Issue by riddlesomebody** [JXA-Cookbook/JXA-Cookbook#45]
I followed the chapter [**Using Objective C (ObjC) with JXA**](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-%28ObjC%29-with-JXA) and tried to import a custom framework as follows,
```
#!/usr/bin/osascript -l JavaScript

ObjC.import('/User/me/demo.framework')
$.Demo.test()
```
but I got an error `execution error: Error on line 2: Error: nothing found to import (-2700)` when executed it.
Is there some special work to the framework that can be imported in JXA?
BTW, the demo.framework's implementation is simple.
```
// demo.h
@interface Demo
+ (void)test;
@end
```
```
// demo.m
#import "demo.h"
@implementation Demo
+(void)test
{
    NSLog(@"Test!");
}
@end
```

**Comment by riddlesomebody** [comment]
> Frameworks need a sdef file that lists all imports and data types. This is not really documented by Apple.

@Tatsh Could you make some examples?
BTW,I also use the commandline tool **gen_bridge_metadata** and try to generate the _.bridgesupport_ file of the framework mentioned before, but the generated file don't contain the description of the Demo class.Is the same reason you mentioned that causes this problem?

**Comment by Tatsh** [comment]
Yes I meant a bridge file. You will probably have to write it manually if you cannot get `gen_bridge_metadata` to work. Since it was part of the Ruby support bridge, it's [considered retired](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/RubyPythonCocoa/Articles/GenerateFrameworkMetadata.html) at this point.

With `gen_bridge_metadata`, I have hit [this bug](https://openradar.appspot.com/40649128) in Mojave and the workaround does not work.

**Comment by riddlesomebody** [comment]
Just create a simple framework.bridgesupport file as follows in the framework's _Resources/BridgeSupport_ directory to solve this problem.
```
<?xml version='1.0'?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version='1.0'/>
```
U even do nothing to export the framework to JXA! GOOD JOB, APPLE! 😭
